black:
  max:
  - 115
  - 135
  - 135
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 255
  - 255
  - 110
  min:
  - 0
  - 0
  - 0
green:
  max:
  - 200
  - 106
  - 211
  min:
  - 0
  - 0
  - 0
red:
  max:
  - 255
  - 255
  - 255
  min:
  - 0
  - 185
  - 0
white:
  max:
  - 255
  - 179
  - 255
  min:
  - 145
  - 110
  - 0
